# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-us'
words_per_minute: 200
excerpt_separator: <!--more-->  # you can specify your own separator, of course.

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Website info
title: Proteiosic Thoughts
description: Personal Blog of Michael S. Huang
cover: assets/images/blog-cover-fractal-cropped.jpg
logo: 
logo_dark: assets/images/favicon.png
favicon: assets/images/favicon.png
url: https://www.proteiosic.com
production_url: https://www.proteiosic.com
source_url: https://github.com/mhuang74-blog/proteiosic
CNAME: www.proteiosic.com

# Social info
navigation: False # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
#twitter: tryghost # replace by your username
facebook: mhuang74

# Disqus
disqus: False
disqus_shortname:  # replace with your disqus username

# Google Analytics
google_analytics:

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-seo-tag]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing main branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "main" otherwise
safe: False
lsi: False
username: mhuang74-blog
repo: proteiosic
branch: main
relative_source: _site/
destination: _site/
production_url:  https://www.proteiosic.com
source_url:  https://github.com/mhuang74-blog/proteiosic

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
